# Generated by Django 3.2.3 on 2021-05-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('accounts', '0002_auto_20210525_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=45)),
                ('accounts_users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account_users')),
            ],
        ),
        migrations.CreateModel(
            name='Events_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('locations_rooms_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locations_rooms')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account_users')),
            ],
        ),
    ]
