# Generated by Django 3.2.3 on 2021-05-28 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20210528_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_events',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events_members',
            name='accounts_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_users_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
