# Generated by Django 3.2.3 on 2021-06-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210603_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
