# Generated by Django 3.2.3 on 2021-06-14 01:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_delete_schedule'),
        ('events', '0006_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('occupied_from', models.DateTimeField()),
                ('occupied_to', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.room')),
            ],
        ),
    ]
