# Generated by Django 3.2.3 on 2021-05-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_teams_has_accounts_users',
            name='accounts_teams_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts_teams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts_teams_has_accounts_users',
            name='accounts_users_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.account_users'),
            preserve_default=False,
        ),
    ]
