# Generated by Django 3.2.3 on 2021-05-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_events',
            name='locations_rooms',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.locations_rooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations_rooms',
            name='locations_locations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.locations_locations'),
            preserve_default=False,
        ),
    ]
