# Generated by Django 3.2.3 on 2021-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210525_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_locations',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
