# Generated by Django 3.2.3 on 2021-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_locations_locations_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations_locations',
            name='size',
        ),
        migrations.AddField(
            model_name='locations_rooms',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
