# Generated by Django 3.2.3 on 2021-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210526_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_events',
            name='occupied_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='locations_events',
            name='occupied_to',
            field=models.DateTimeField(null=True),
        ),
    ]
