# Generated by Django 3.2.3 on 2021-06-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_schedule_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
